# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# config_hash.rb
#

# ---- original file header ----
#
# @summary
#   This function ensures the proper structure for git configuration options.
#*Examples:*
#    git_config_hash({"foo" => 1, "bar" => {"value" => 2}})
#Would return: {"foo" => {"value" => 1}, "bar" => {"value" => 2}}
#
#
Puppet::Functions.create_function(:'git::git_config_hash') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    raise(Puppet::ParseError, "git_config_hash(): Wrong number of arguments " +
      "given (#{arguments.size} for 1)") if arguments.size < 1

    configs = arguments[0]

    unless configs.is_a?(Hash)
      raise(Puppet::ParseError, 'git_config_hash(): Requires hash to work with')
    end

    return Hash[configs.map {|k, v| [k, v.is_a?(Hash) ? v : {"value" => v}] }]
  
  end
end
